// @flow

export { getWallet } from './getWallet'
export { getAddress } from './getAddress'
export { getMnemonic } from './getMnemonic'
export { getAddresses } from './getAddresses'
export { appendWallet } from './appendWallet'
export { createWallet } from './createWallet'
export { removeWallet } from './removeWallet'
export { updateWallet } from './updateWallet'
export { upgradeWallet } from './upgradeWallet'
export { getBackupData } from './getBackupData'
export { getPrivateKey } from './getPrivateKey'
export { getTypeByInput } from './getTypeByInput'
export { checkMnemonicType } from './checkMnemonicType'
export { checkWalletUniqueness } from './checkWalletUniqueness'
